name: 定时拉取源代码版本

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0,20,40 * * * *"
  workflow_dispatch:
    inputs:
      force:
        description: "强制拉取最新版本"
        required: true
        default: false
        type: boolean

jobs:
  compare-versions:
    runs-on: ubuntu-latest
    outputs:
      TRIGGER_ACTION: ${{ steps.compare-versions.outputs.TRIGGER_ACTION }}

    steps:
      - name: 获取最新版本信息
        id: get-version
        uses: fjogeleit/http-request-action@v1
        with:
          url: "https://cx-api.waadri.top/get_other_node_version.json"
          method: "GET"
          timeout: 90000

      - name: 接口响应
        run: echo "${{ steps.get-version.outputs.response }}"

      - name: 设置版本号
        id: parse-response
        run: |
          echo "VERSION=${{ fromJson(steps.get-version.outputs.response).latest_version }}" >> $GITHUB_ENV
          echo "URL=${{ fromJson(steps.get-version.outputs.response).docker_download_url }}" >> $GITHUB_ENV

      - name: 获取当前 GitHub 发布版本
        id: get-release-version
        run: |
          release_version=$(curl -s https://api.github.com/repos/Misaka-1314/SignNode-AutoBuild/releases/latest | jq -r .tag_name)
          echo "CURRENT_RELEASE_VERSION=$release_version" >> $GITHUB_ENV
          echo "CURRENT_RELEASE_VERSION=${release_version}"

      - name: 比较版本
        id: compare-versions
        run: |
          echo "当前版本=v${{ env.VERSION }} 已构建版本=${{ env.CURRENT_RELEASE_VERSION }}"

          if [[ "v${VERSION}" != "${CURRENT_RELEASE_VERSION}" || "${{ github.event.inputs.force }}" == "true" ]]; then
            echo "版本更新，触发新的 Action"
            echo "TRIGGER_ACTION=true" >> "$GITHUB_OUTPUT"
            echo "TRIGGER_ACTION=true" >> "$GITHUB_ENV"
          fi

      - name: 安装 Python
        uses: actions/setup-python@v5

      - name: 拉取最新代码
        if: github.event.inputs.force == 'true' || env.TRIGGER_ACTION == 'true' || github.event_name == 'push'
        run: |
          wget -O "main.py" "${{ env.URL }}"
          wget -O "replace.py" "https://raw.githubusercontent.com/Misaka-1314/SignNode-AutoBuild/main/resource/replace.py"
          wget -O "waadri.ico" "https://raw.githubusercontent.com/Misaka-1314/SignNode-AutoBuild/main/resource/waadri.ico"
          wget -O "Dockerfile" "https://raw.githubusercontent.com/Misaka-1314/SignNode-AutoBuild/main/resource/Dockerfile"
          wget -O ".dockerignore" "https://raw.githubusercontent.com/Misaka-1314/SignNode-AutoBuild/main/resource/.dockerignore"
          wget -O "requirements.txt" "https://raw.githubusercontent.com/Misaka-1314/SignNode-AutoBuild/main/resource/requirements.txt"
          echo "v${{ env.VERSION }}" > version.txt

          python replace.py

      - name: 上传 Python 代码
        if: github.event.inputs.force == 'true' || env.TRIGGER_ACTION == 'true' || github.event_name == 'push'
        uses: actions/upload-artifact@v4
        with:
          name: main-v${{ env.VERSION }}.py
          path: ./main.py

      - name: 提交文件
        if: github.event.inputs.force == 'true' || env.TRIGGER_ACTION == 'true' || github.event_name == 'push'
        run: |
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add . && git commit -m "更新代码"

      - name: 推送到 GitHub
        if: github.event.inputs.force == 'true' || env.TRIGGER_ACTION == 'true' || github.event_name == 'push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          force: true
          directory: .

  call_workflow-1:
    needs: compare-versions
    if: github.event.inputs.force == 'true' || needs.compare-versions.outputs.TRIGGER_ACTION == 'true' || github.event_name == 'push'
    uses: Misaka-1314/SignNode-AutoBuild/.github/workflows/docker-image.yaml@main
    secrets:
      TENCENT_CCR_USERNAME: ${{ secrets.TENCENT_CCR_USERNAME }}
      TENCENT_CCR_PASSWORD: ${{ secrets.TENCENT_CCR_PASSWORD }}
      DOCKER_REGISTRY_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

  call_workflow-2:
    needs: compare-versions
    if: github.event.inputs.force == 'true' || needs.compare-versions.outputs.TRIGGER_ACTION == 'true' || github.event_name == 'push'
    uses: Misaka-1314/SignNode-AutoBuild/.github/workflows/pyinstaller.yaml@main
