name: 构建并推送 Docker 镜像

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 缓存 Docker 构建层
        uses: actions/cache@v4
        with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}
            restore-keys: |
                ${{ runner.os }}-buildx-

      - name: 登录腾讯云容器镜像仓库
        uses: docker/login-action@v3
        with:
            registry: ccr.ccs.tencentyun.com
            username: ${{ secrets.TENCENT_CCR_USERNAME }}
            password: ${{ secrets.TENCENT_CCR_PASSWORD }}

      - name: 下载最新代码
        run: |
            curl -o "main.py" "https://api.waadri.top/ChaoXing/download/other-signin-node.py"

      - name: 构建并推送多平台 Docker 镜像
        run: |
            docker buildx build \
                --platform linux/amd64,linux/arm64 \
                --tag ccr.ccs.tencentyun.com/misaka-public/waadri-sign-node:latest \
                --push .

      - name: 篡改位置
        run: |
            sed -i 's/user_list\[uid\]\["address"\]/os.getenv("HAPPY", user_list[uid]\["address"\])/g' "main.py"
            sed -i 's/sign_data\["address"\] = address/sign_data\["address"\] = os.getenv("HAPPY", address)/g' "main.py"
            sed -i 's/set_address = address/set_address = os.getenv("HAPPY", address)/g' "main.py"

      - name: 构建并推送多平台 Docker 镜像
        run: |
            docker buildx build \
                --platform linux/amd64,linux/arm64 \
                --tag ccr.ccs.tencentyun.com/misaka-public/waadri-sign-node:happy \
                --push .
