name: 构建并推送 Docker 镜像

on:
    workflow_call:
        secrets:
            TENCENT_CCR_USERNAME:
                required: true
            TENCENT_CCR_PASSWORD:
                required: true
            DOCKER_REGISTRY_PASSWORD:
                required: true

jobs:
    docker-image:
        runs-on: ubuntu-latest

        steps:
            - name: 检出代码
              uses: actions/checkout@v4
              with:
                  ref: dev

            - name: 设置 Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: 缓存 Docker 构建层
              uses: actions/cache@v4
              with:
                  path: /tmp/.buildx-cache
                  key: ${{ runner.os }}-buildx-${{ github.sha }}
                  restore-keys: |
                      ${{ runner.os }}-buildx-${{ github.sha }}

            - name: 登录 Docker Hub 容器镜像服务
              uses: docker/login-action@v3
              with:
                  username: misaka1314
                  password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

            - name: 登录腾讯云容器镜像仓库
              uses: docker/login-action@v3
              with:
                  registry: ccr.ccs.tencentyun.com
                  username: ${{ secrets.TENCENT_CCR_USERNAME }}
                  password: ${{ secrets.TENCENT_CCR_PASSWORD }}

            - name: 获取版本号
              id: fetch-version
              run: echo "VERSION=$(cat ./version.txt)" > $GITHUB_ENV

            - name: 构建并推送多平台 Docker 镜像
              run: |
                  docker buildx build \
                      --file ./Dockerfile \
                      --label image.source=自动签到节点 \
                      --label image.version=${{ env.VERSION }} \
                      --platform linux/amd64,linux/arm64 \
                      --tag ccr.ccs.tencentyun.com/misaka-public/waadri-sign-node:latest \
                      --tag ccr.ccs.tencentyun.com/misaka-public/waadri-sign-node:${{ env.VERSION }} \
                      --tag misaka1314/waadri-sign-node:latest \
                      --tag misaka1314/waadri-sign-node:${{ env.VERSION }} \
                      --push .
