name: 文档发布

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 签出代码
        uses: actions/checkout@v4
        with:
          ref: main

      - name: 安装依赖
        run: npm i -D --force
        working-directory: docs

      - name: 构建文档
        run: npm run docs:build
        working-directory: docs

      - name: 签出原文件
        uses: actions/checkout@v4
        with:
          ref: main
          path: docs/.vuepress/dist/temp
          fetch-depth: 0

      - name: 操作文件
        run: |
          mkdir source && cp -r temp/docs/* ./source
          rm -rf temp
        working-directory: docs/.vuepress/dist

      - name: 提交文件
        run: |
          git init
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add . && git commit -m "更新文档"
        working-directory: docs/.vuepress/dist

      - name: 推送到 GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: pages
          force: true
          directory: docs/.vuepress/dist
